### ISSUE TITLE
Feature  Limit on maps that can be created.

### ISSUE THREAD

**Issue by Aridean** [drbot7/DrMap#10]
Firstly. Plugin works great.  No real complaints.

One thing I would like to see added would be a way to limit how many maps can be created per user. 
I want to be able to let players create their own maps, but would rather not have them run wild creating maps willy nilly.

Not sure how hard it would be to impliment, but ideally, this would be implemented via a permission.
Something along the lines of 
'drmap.command.create.<max number>'

Alternatively, it could also be done in the configuration file, with the option to let OP bypass the limit if that makes sense.

**Comment by akdukaan** [comment]
What's wrong with someone creating hundreds of maps? What problem does this solve? Should it still count toward their limit if they create a map and then trash the map? Or if the map gets stolen by another player?

**Comment by akdukaan** [comment]
Closing as stale
